### ISSUE TITLE
Question: How to use an EC2 Instance role for accessing S3/DynamoDB?

### ISSUE THREAD

**Issue by xenji** [delta-io/kafka-delta-ingest#111]
I cannot find any reference to the default credential chain in the code, can anyone help me?

**Comment by mosyp** [comment]
Hi! It's managed by delta-rs and rusoto-s3, the default instance creds should work just fine. In addition you can even assume role via sts, please see https://github.com/delta-io/delta-rs/blob/main/rust/src/storage/s3/mod.rs#L30-L86
