### ISSUE TITLE
No snapshot or version 0 found

### ISSUE THREAD

**Issue by timopetmanson** [delta-io/kafka-delta-ingest#130]
Hello guys, I'm trying to set up `kafka-delta-ingest` with AWS S3, but get an error
```
Ingest service exited with error DeltaTable { source: NotATable("No snapshot or version 0 found, perhaps s3://mybucket/rust-deltalake/raw.test.mytopic is an empty dir?") }
```

I'm running the command in a local Docker container using a local Kafka broker.
```
command: ["/usr/local/bin/kafka-delta-ingest", "ingest",
              "raw.test.mytopic",                                                   
              "s3://mybucket/rust-deltalake/raw.test.mytopic", 
              "--allowed_latency", "300",
              "--kafka", "host.docker.internal:9092",
              "--consumer_group_id", "my_consumer_group"]
```

Did I miss a step or a configuration option? Should I create the empty deltalake myself?

Thanks,
T

**Comment by houqp** [comment]
Did you create the table before running kdi?

**Comment by timopetmanson** [comment]
Hi @houqp, I did not create the delta table before running KDI. I was hoping that KDI would create a table if necessary.
That said, are there any scripts/tools for creating an empty table that you would recommend does does not require Spark?

**Comment by timopetmanson** [comment]
But closing the ticket as I got my answer that KDI already expects the table to be present :) Thanks.

**Comment by houqp** [comment]
@timopetmanson you can use spark or the [native deltalake python library](https://delta-io.github.io/delta-rs/python/usage.html#writing-delta-tables) to create it.

**Comment by Jaegin** [comment]
Hi @houqp - I am using Azure Event Hubs and am coming across the same error, even though I have followed the instructions to create the web_requests delta table, i.e.

Create the _delta_log directory in the web_requests directory in Azure Storage and upload the [first Delta transaction containing the schema](https://github.com/delta-io/kafka-delta-ingest/blob/main/tests/data/web_requests/_delta_log/00000000000000000000.json) to this directory.

Any suggestions on how to resolve this issue - appreciate any help you can offer.

**Comment by Jaegin** [comment]
The issue above related to the delta table uri; instead of using "adls2", it should be "abfss".
