### ISSUE TITLE
unable to run example code: "thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:91:18"

### ISSUE THREAD

**Issue by clairewood** [delta-io/kafka-delta-ingest#146]
Hi! I'm back again. Again, apologies if this ends up being my own error/misunderstanding, I'm very new here!

When I try following the "Starting Worker Processes" steps in the Using Azure Event Hubs section of the README, I get this error:
`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:91:18`

Full input and error:

```
$ RUST_LOG=debug cargo run ingest \
>   --allowed_latency 60 \
>   --app_id web_requests \
>   --transform 'date: substr(meta.producer.timestamp, `0`, `10`)' \
>   --transform 'meta.kafka.offset: kafka.offset' \
>   --transform 'meta.kafka.partition: kafka.partition' \
>   --transform 'meta.kafka.topic: kafka.topic' \
>   --auto_offset_reset earliest \
> web_requests ./tests/data/web_requests
    Finished dev [unoptimized + debuginfo] target(s) in 1.04s
     Running `target\debug\kafka-delta-ingest.exe ingest --allowed_latency 60 --app_id web_requests --transform 'date: substr(meta.producer.timestamp, `0`, `10`)' --transform 'meta.kafka.offset: kafka.offset' --transform 'meta.kafka.partition: kafka.partition' --transform 'meta.kafka.topic: kafka.topic' --auto_offset_reset earliest web_requests ./tests/data/web_requests`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src\main.rs:91:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\kafka-delta-ingest.exe ingest --allowed_latency 60 --app_id web_requests --transform 'date: substr(meta.producer.timestamp, `0`, `10`)' --transform 'meta.kafka.offset: kafka.offset' --transform 'meta.kafka.partition: kafka.partition' --transform 'meta.kafka.topic: kafka.topic' --auto_offset_reset earliest web_requests ./tests/data/web_requests` (exit code: 101)      
```

The error seems to occur with unwrapping the seek_offsets argument ID in main.rs. None of the examples show anyone using the seek_offsets argument. Based on that and my poking around in the code, I thought that one was optional to use, so I'm not sure how it's ending up with a None value. 

I have tried using seek_offsets but I'm having trouble getting the format down for how to use it. 

I have also tried following the steps in the README for Using Azure Event Hubs in order to connect my existing Kafka stream (in an Event Hub instance) to a delta table (in ADLS) but I'm getting the same exact error. 

It seems like I'm the only one encountering these errors -- is there another version of KDI I should be using? Is there something I should've done besides just forking and cloning KDI then just starting to follow the README instructions? 

If someone is able to help I would really appreciate it! Thank you.

**Comment by mightyshazam** [comment]
It appears there are more issues than we initially thought with the clap upgrade. I'm looking through them now. We should be able to put together a fix shortly. However, if you are looking for an example for `seek_offsets`, there is a test in the code for the parser. It takes a json map like the following `{"0":10,"2":12,"1":13}`

**Comment by clairewood** [comment]
Thank you for looking into it, and for pointing me in the right direction for the json map! I will wait for the fix before trying it again.
