### ISSUE TITLE
Is there support to read images/videos from kafka and push to delta lake

### ISSUE THREAD

**Issue by asksonu** [delta-io/kafka-delta-ingest#148]
Is there support to read images/videos from kafka and push to delta lake ?

**Comment by rtyler** [comment]
@asksonu there is not at present, I'm curious what the message format in Kafka would look like for your needs?

**Comment by asksonu** [comment]
@rtyler , thanks for your response. Use case is to upload image or video with some meta data. I found someother means to satisfy my use-case. thanks.
