### ISSUE TITLE
end_at_last_offsets flag is always set

### ISSUE THREAD

**Issue by kyrre** [delta-io/kafka-delta-ingest#158]
The following always evaluates to true:

https://github.com/delta-io/kafka-delta-ingest/blob/3eac101bccd0b3900374004384444ae6cd43f98a/src/main.rs#L138

https://github.com/delta-io/kafka-delta-ingest/blob/3eac101bccd0b3900374004384444ae6cd43f98a/src/main.rs#L425-L430

I have no idea why this happens, but the same issue is discussed in this [post](https://stackoverflow.com/questions/74905313/why-is-this-branch-always-true-using-clap-4) and seems to be related to clap4.

**Comment by rtyler** [comment]
I believe @mightyshazam fixed this with #159
