### ISSUE TITLE
What is the documentation to use HMS as the catalog with delta lake on S3?

### ISSUE THREAD

**Issue by alberttwong** [delta-io/kafka-delta-ingest#174]
I can't seem to find instructions on how to write delta lake files on S3 or register them in HMS.

The closest I've found is using Apache xTable to covert iceberg or hudi on s3 into Delta Lake on s3 and then register those files in HMS.   https://github.com/StarRocks/demo/tree/master/documentation-samples/datalakehouse

**Comment by rtyler** [comment]
This is a question better posted in the delta-users slack

**Comment by alberttwong** [comment]
My concern with delta-users slack is that this should be documented, and lots of stuff on stack isn't "official."
