### ISSUE TITLE
Ability to not use write-ahead-log

### ISSUE THREAD

**Issue by HamiltonHord** [delta-io/kafka-delta-ingest#19]
There can be cases where we wouldn't want the extra overhead of dynamo-db, with the understanding of increasing risk of data-duplication. 

This would mean relying entirely on the Kafka consumer offsets for restarts and recoveries.

**Comment by xianwill** [comment]
FYI - we are completely moving away from the write ahead log implementation and relying on a neat trick within the Delta log instead. I will close this issue once that work goes in. I'll leave this open for now in case we encounter any major issue with the alternative implementation.
