### ISSUE TITLE
Add commit loop with conflict resolution for txn actions

### ISSUE THREAD

**Issue by xianwill** [delta-io/kafka-delta-ingest#25]
https://github.com/delta-io/kafka-delta-ingest/pull/23 replaces the write ahead log with a txn per partition written to the delta log :tada:. After this is merged, we must follow up with another change to add a retry loop in case two workers try to commit the same delta log version and one fails. The failing worker will need to do conflict resolution in case of overlapping partition assignment between the two commits.

**Comment by mosyp** [comment]
I just want to point out, primarily for myself, that the overlapping partition assignment between the two commits means the conflict offsets for the same partition between different workers. So if one consume will win in acquiring the lock, then the other one should clear data for that partition which is not yet implemented.
