### ISSUE TITLE
Build Error on Windows Machine: Failed to run custom build command for openssl-sys v0.9.61 

### ISSUE THREAD

**Issue by rajatha-ravish** [delta-io/kafka-delta-ingest#42]

**Comment by houqp** [comment]
@rajatha-ravish could you paste the full console error here?

**Comment by rajatha-ravish** [comment]
error: failed to run custom build command for `openssl-sys v0.9.61`

Caused by:
  process didn't exit successfully: `C:\kafka-delta-ingest\target\debug\build\openssl-sys-6186f04521601717\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\kafka-delta-ingest\\target\\debug\\build\\openssl-sys-0796760039d4b93b\\out\\openssl-build\\install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', C:\Users\Rajatha Ravish\scoop\persist\rustup\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-111.15.0+1.1.1k\src\lib.rs:469:39
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by houqp** [comment]
have you tried following the instructions in https://docs.rs/crate/openssl-sys/0.9.19? Alternatively, you can try rustls flag to avoid linking against openssl, see: https://github.com/delta-io/delta-rs/blob/main/rust/Cargo.toml#L60.

**Comment by rajatha-ravish** [comment]
I have tried installing the SSl certificate as instructed in the first link and with other third-party. It did not help. 

Trying alternative -

Lines I added : 

[features]
rustls = ["rusoto_core/rustls", "rusoto_credential", "rusoto_s3/rustls", "rusoto_sts/rustls", "rusoto_dynamodb/rustls", "maplit"]

error: failed to parse manifest at `C:\workspace\kafka-delta-ingest\Cargo.toml`

Caused by:
  feature `rustls` includes `rusoto_credential`, but `rusoto_credential` is not an optional dependency
  A non-optional dependency of the same name is defined; consider adding `optional = true` to its definition.

**Comment by houqp** [comment]
You need to add `optional = true` to all the dependencies mentioned in that list. For example: https://github.com/delta-io/delta-rs/blob/main/rust/Cargo.toml#L36.

You also need to add `"deltalake/s3-rustls"` to the list.

**Comment by houqp** [comment]
@rajatha-ravish I recommend going through https://doc.rust-lang.org/cargo/reference/features.html to get a better understanding of how feature flag works in cargo.

**Comment by rajatha-ravish** [comment]
I have made the recommended changes, cargo build fails again. 


Changes made : 

maplit = { version = "1", optional = true }

rusoto_core = { version = "0.46", optional = true }
rusoto_credential = { version = "0.46" , optional = true }
rusoto_s3 = { version = "0.46", optional = true }

deltalake = { version = "0.4.0", git = "https://github.com/delta-io/delta-rs.git", rev = "ddc123c0be9def306edafbb972f773baaefc40ad", features = ["s3"], optional =true }

[features]
s3-rustls = ["rusoto_core/rustls", "rusoto_credential", "rusoto_s3/rustls", "deltalake/s3-rustls", "maplit"]


error: failed to run custom build command for `openssl-sys v0.9.61`
Caused by:
  process didn't exit successfully: `C:\demo\kafka-delta-ingest\target\debug\build\openssl-sys-6186f04521601717\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\demo\\kafka-delta-ingest\\target\\debug\\build\\openssl-sys-0796760039d4b93b\\out\\openssl-build\\install" "no-dso" "no-shared" "no-ssl3" "no-unit-test" "no-comp" "no-zlib" "no-zlib-dynamic" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-engine" "no-asm" "VC-WIN64A"

**Comment by houqp** [comment]
what command did you run to build the project? did you pass in `s3-rustls` feature flag to the build command? looks like it's still trying to build openssl. I would remove the `s3` feature from `deltalake` as well to make sure it's only using rustls.
