### ISSUE TITLE
Kafka-connect sink connector

### ISSUE THREAD

**Issue by raphaelauv** [delta-io/kafka-delta-ingest#51]
Hello, I would like to know if it's in the roadmap of this project to work on a kafka-connect sink connector more than a daemon.

kafka -> deltaLakeSinkConnector -> deltaLake

Thank you all

**Comment by houqp** [comment]
kafka connector is out of scope for this project. kafka-delta-ingest is designed to work without external dependencies so it's easier to manage and operate.

**Comment by raphaelauv** [comment]
Thanks for the quick answer, I will make a try on my side.

**Comment by raphaelauv** [comment]
confluent is wokring with databricks with one implementation but it's not open source.

https://www.confluent.io/blog/migrate-data-to-the-cloud-with-confluent-and-databricks-connector/?utm_source=twitter&utm_medium=organicsocial&utm_campaign=tm.devx_ch.bp-migrate-data-from-on-premises-data-platforms-to-databricks-delta-lake-in-aws_content.solutions
